from pathlib import Path
import json,collections,hashlib,shutil,zipfile
R=Path(__file__).resolve().parent;O=R.parent/'outputs';B=R/'revision-0.1.2';RUN=B/'runs/20260913T022729Z-05c9476b'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
records=[json.loads(l) for l in (RUN/'records.jsonl').read_text(encoding='utf-8').splitlines()];traces=[json.loads(l) for l in (RUN/'traces.jsonl').read_text(encoding='utf-8').splitlines()]
accept=read(R/'assessment-3/trace_acceptance_records.json');tx=read(R/'transaction-audit-0.1.2/records.json');parents=read(B/'parent_inventory.json')
counts=collections.Counter(c['Status'] for c in records);kinds=collections.Counter(c['Kind'] for c in records if c['Status']!='Not run')
rows=[]
for oracle in ['O1','O2','O3','O4','O5','End-to-End']:
 subset=[c for c in records if oracle in c['Oracles']];ct=collections.Counter(c['Status'] for c in subset)
 rows.append({'Oracle':oracle,'Planned':len(subset),'Executed':sum(c['Status']!='Not run' for c in subset),'Pass':ct['Pass'],'Fail':ct['Fail'],'Unresolved':ct['Unresolved'],'Not run':ct['Not run']})
admissions=[t for t in traces if t['Stage']=='Admission' and 'invariants' in t]
inv=[{'Invariant':f'INV-{i+1:02}','RecordedPredicateEvaluations':len(admissions),'AdmittedViolations':sum(t.get('admitted') is True and t['invariants'][i] is False for t in admissions),'UnknownOnAdmitted':sum(t.get('admitted') is True and t['invariants'][i] is None for t in admissions)} for i in range(5)]
pc={c['ParentCaseID'] for c in records if c['Status']!='Not run'};fc={c['ChildFamilyID'] for c in records if c['Status']!='Not run' and c['ChildFamilyID']}
summary={'Build':'UAIS-HEADLESS-0.1.2','RunID':RUN.name,'InventoryEntries':len(records),'ExecutableCases':sum(c['Status']!='Not run' for c in records),'Pass':counts['Pass'],'Fail':counts['Fail'],'Unresolved':counts['Unresolved'],'NotRunEntries':counts['Not run'],'SelectedDeterministicAgreementPercent':100*counts['Pass']/sum(c['Status']!='Not run' for c in records),'Oracles':rows,'CaseKinds':dict(kinds),'ParentsRepresented':len(pc),'ParentsTotal':35,'CurrentChildFamiliesRepresented':len(fc),'CurrentChildFamiliesTotal':44,'CoverageCaution':'Presence of a linked instance is not full branch/effect coverage; universe of remaining concrete parameter/scope instances is not fully enumerated.','InvariantMetrics':inv,'AppliedInvariantViolationsObserved':sum(i['AdmittedViolations'] for i in inv),'StaleDecisionPreventions':sum(isinstance(c['ObservedOutcome'],dict) and c['ObservedOutcome'].get('stale_prevented') is True for c in records),'DuplicateTransactionEffectsObserved':sum(max(0,c['ObservedOutcome'].get('effects',0)-1) for c in records if isinstance(c['ObservedOutcome'],dict)),'TraceAcceptanceFailuresFinal':sum(a['Status']=='Fail' for a in accept),'TraceAcceptanceFailuresInitial':8,'TransactionAcceptanceFailuresIntermediate':5,'SpecificationDefectsDiscovered':0,'ConfirmedImplementationDefectsDiscovered':3,'Recommendation':'SECTION 6 NOT YET SUPPORTED'}
(O/'UAIS_Section6_Coverage_Summary.json').write_text(json.dumps(summary,indent=2),encoding='utf-8')
defect={'SpecificationDefectsDiscovered':0,'ImplementationDefectsDiscovered':3,'Entries':[
 {'DefectID':'IMPL-001','Component':'instrumentation','OriginalEvidence':'assessment-1/trace_acceptance_records.json: eight failed required-field audits','Correction':'0.1.1 records versions, plan inputs, current/source tokens and deferred supersession','Retest':'assessment-2 and assessment-3: 8/8 checks pass','Status':'CLOSED FOR CHECKED MODEL TRACE REQUIREMENTS'},
 {'DefectID':'HARNESS-001','Component':'trace checker','OriginalEvidence':'0.1.0 stage-presence check passed eight traces that failed stricter acceptance','Correction':'0.1.1 required-field checks; separate acceptance checker and missing-version/token/parent negative controls','Retest':'eight accepted traces and three rejected corruptions in assessment-3','Status':'CLOSED FOR CHECKED STRUCTURAL REQUIREMENTS'},
 {'DefectID':'IMPL-002','Component':'transaction branch and feedback','OriginalEvidence':'transaction-audit-0.1.1: two incorrect terminal retry dispositions and five absent feedback records, yielding five failed branch assessments','Correction':'0.1.2 supplies known-negative terminal retry guard and mandatory baseline feedback, with pending feedback following retry dispatch','Retest':'transaction-audit-0.1.2: 5/5 pass with unchanged TX-1 expectations','Status':'CLOSED FOR FIVE CHECKED BRANCHES'},
 {'DefectID':'LIMIT-001','Component':'full canonical comparator domain','Evidence':'Known NFC-string-only canonical key; complete typed tuple/decimal/set normalisation unimplemented','Status':'OPEN; GAP/canonical-typed-domain'},
 {'DefectID':'COVERAGE-001','Component':'remaining verification domain','Evidence':'Five explicit gap entries; browser, complete action effects/scopes, full canonical domain, fully justified rule-mask scenarios, and IME/browser observation','Status':'OPEN'},
 {'DefectID':'COVERAGE-002','Component':'parent/family linkage','OriginalEvidence':'34/35 parents and 41/44 child families in 0.1.0','Correction':'Six added instances in dataset 0.1.1','Retest':'35/35 parents and 44/44 families represented by at least one current instance','Status':'LINKAGE CLOSED; FULL SEMANTIC COVERAGE NOT IMPLIED'}], 'OraclePolicy':'Governing specifications unchanged. Existing expected objects retained; six new instances added in a versioned dataset. Acceptance rules apply original TRACE/TX-1 requirements; initial weak-check passes and subsequent failures remain preserved.'}
(O/'UAIS_Section6_Defect_Retest_Register.json').write_text(json.dumps(defect,indent=2),encoding='utf-8')
notes={'O1':'Synthetic input classification; reflow/feature witnesses injected, not measured in a browser.','O2':'252 C→N, 112 N→R, 24 assistance-state edge checks, 144 action-gate branches; additional enum/variant/sequence cases. Predicate extraction and complete effects remain bounded.','O3':'Fixed plan/set witnesses, closed composition examples and semantic scopes; full typed canonical domain not run.','O4':'Ordered event and transaction/state model; no distributed/browser concurrency experiment.','O5':'Model state and reachability checks, plus deliberate rejected-mutation controls; no browser preservation claim.','End-to-End':'Selected model chains; eight traces additionally checked against required fields, five transaction branches audited separately.'}
table=['# Section 6 observed result tables','','Counts below are from the final frozen build run, not expected results. Oracle rows overlap because one case can have several oracle tags. The inventory is a bounded expansion, not the complete space of all possible VER-CAT1 inputs.','','## Table 10. Verification coverage by oracle','','| Oracle | Planned entries | Executed | Pass | Fail | Unresolved | Not run | Coverage notes |','| --- | --- | --- | --- | --- | --- | --- | --- |']
for r in rows:table.append('| '+' | '.join(str(r[k]) for k in ['Oracle','Planned','Executed','Pass','Fail','Unresolved','Not run'])+' | '+notes[r['Oracle']]+' |')
table+=['',f'Unique inventory: {len(records)} entries; {counts["Pass"]} executed deterministic cases match their frozen expected objects, 0 mismatches and 0 unresolved executions; 5 explicit gap entries are not run. Agreement on this selected executable inventory is 100%. This is not a framework-wide pass rate. Acceptance audits and checker negative controls are reported separately rather than pooled into that denominator.','','## Table 11. Representative resolver cases','','| Case | Candidate/plan situation | Relevant criteria | Expected | Observed | Result |','| --- | --- | --- | --- | --- | --- |']
for name in ['O3/compose/compatible','O3/compose/shared','O3/compose/guidance','O3/stage/True','O3/compose/text','O3/compose/review','O3/reduce/narrow','O3/reduce/none']:
 c=next(c for c in records if c['TestCaseID']==name);table.append(f"| {name} | {', '.join(c['Input'].get('actions',c['Input'].get('selected',[])))} | Admission, permitted realisation and compatibility | {c['ExpectedOutcome']['operation']} | {c['ObservedOutcome']['operation']} | {c['Status']} |")
for label in ['coverage','incomparable','lower-after-incomparable','tie','unknown']:
 c=next(c for c in records if c['TestCaseID'].startswith('O3/resolver/'+label+'/'));table.append(f"| {label} | Explicit scoped plan witnesses | Six ordered criteria | {c['ExpectedOutcome']} | {c['ObservedOutcome']} | {c['Status']} |")
table+=['','## Table 12. Invariant results','','| Invariant | Logged predicate evaluations at admission | Violations on admitted transitions | Evidence and boundary |','| --- | --- | --- | --- |']
for r in inv:table.append(f"| {r['Invariant']} | {r['RecordedPredicateEvaluations']} | {r['AdmittedViolations']} | Admission records in final traces; model state only |")
table+=['','The five predicates are recorded together at each listed admission. Their counts are not independent scenario counts. Deliberate corrupt-state/reachability probes are negative oracle controls, not applied changes: expected false predicates are detections rather than observed adaptation-induced violations. These local predicates do not establish complete enforcement of every service constraint or actual DOM/IME preservation.','','## Table 13. Transaction branch results','','| Branch | Query status evidence | Retry disposition | New retry attempts | Logical identities | Committed effects | Recorded feedback | Acceptance |','| --- | --- | --- | --- | --- | --- | --- | --- |']
for a in tx:
 branch=a['TestCaseID'].split('/')[-1];c=next(c for c in records if c['TestCaseID']=='TX/'+branch);v=c['ObservedOutcome']
 table.append(f"| {branch} | {v['status']} | {a['ObservedOutcome']['retry']} | {int(v['retry'])} | {v['identities']} | {v['effects']} | {a['ObservedOutcome']['feedback']} | {a['Status']} |")
table+=['','Each branch has one initial simulated submission attempt and one read-only query. Total submission attempts are two for X-R and one for the other branches. X-C starts with one already committed effect despite response loss; its query adds no effect. X-R commits during the admitted simulated retry, but feedback remains pending until a later completion response. Feedback here is a machine-readable baseline service output, not a rendered UI assessment.','','## Table 14. Trace reconstruction acceptance','','| Scenario | Required stages | Observed stages | Missing required fields at final audit | Initial strict acceptance | Final strict acceptance |','| --- | --- | --- | --- | --- | --- |']
for a in accept:table.append(f"| {a['TestCaseID'].replace('ACCEPT/TRACE/','')} | 10 | {a['CompleteStages']} | {len(a['ObservedOutcome']['missing_required_fields'])} | Fail | {a['Status']} |")
table+=['','The ten stages are Observation, Context, C→N edge, Need, N→R edge, Rule, Action, Resolver, Admission and Result. The acceptance checker also checks version links, resolver inputs, admission vectors/tokens and deferred supersession. Three negative controls remove a version, a token or a parent reference; all three corruptions are rejected. This establishes the checked trace structure within these model scenarios, not independent validation of every logged semantic assertion.']
(O/'UAIS_Section6_Result_Tables.md').write_text('\n'.join(table)+'\n',encoding='utf-8')
shutil.copyfile(B/'execution_manifest.json',O/'UAIS_Section6_Execution_Manifest.json')
print(json.dumps(summary,indent=2))
