from pathlib import Path
import json,collections,hashlib,shutil
R=Path(__file__).resolve().parent;O=R.parent/'outputs';B=R/'closure-0.2.2'
def lines(p):return [json.loads(l) for l in p.read_text(encoding='utf-8').splitlines()]
reg=lines(B/'runs/20260913T030324Z-075d96fc/records.jsonl');new=lines(B/'closure_runs/20260913T030322Z-8f183b76/records.jsonl')
old=lines(R/'revision-0.1.2/runs/20260913T022729Z-05c9476b/records.jsonl')
old_exec={c['TestCaseID']:c for c in old if c['Status']!='Not run'};reg_exec={c['TestCaseID']:c for c in reg if c['Status']!='Not run'}
assert set(old_exec)==set(reg_exec) and len(old_exec)==770
assert all(c['ExpectedOutcome']==reg_exec[id]['ExpectedOutcome'] for id,c in old_exec.items())
allcases=list(reg_exec.values())+new;assert len({c['TestCaseID'] for c in allcases})==868
assert all(c['Status']=='Pass' for c in allcases)
manifest=json.loads((B/'execution_manifest.json').read_text(encoding='utf-8'))
for build in [R,R/'revision-0.1.1',R/'revision-0.1.2',R/'closure-0.2.0',R/'closure-0.2.1',B]:
 m=json.loads((build/'execution_manifest.json').read_text(encoding='utf-8'))
 for f,h in m['hashes'].items():assert hashlib.sha256((build/f).read_bytes()).hexdigest()==h,(str(build),f)
original_zip=O/'UAIS_Section6_Execution_Evidence_Package.zip'
archive_status='not present in current workspace; original source/run files and recorded checksum retained'
if original_zip.exists():
 assert hashlib.sha256(original_zip.read_bytes()).hexdigest()=='f2edda937b06f711228819b365e8caeeb8ebbc5e6e7fa1bf2327180a33d36278'
 archive_status='original ZIP byte hash verified unchanged'
for p in (R/'specs').glob('UAIS*'):
 if (O/p.name).exists():assert p.read_bytes()==(O/p.name).read_bytes(),p.name
oracles=[]
for oracle in ['O1','O2','O3','O4','O5','End-to-End']:
 cases=[c for c in allcases if oracle in c['Oracles']];oracles.append({'Oracle':oracle,'PlannedExecutable':len(cases),'Executed':len(cases),'Pass':sum(c['Status']=='Pass' for c in cases),'Fail':sum(c['Status']=='Fail' for c in cases),'Unresolved':0,'NotRunInDeclaredDomain':0})
gaps=[{'OriginalID':'GAP/browser-reflow','Disposition':'RETAINED AS EXPLICIT BOUNDARY','Basis':'Controlled C2.2/reachability witnesses; acquisition and rendering are outside this evaluated semantic domain.'},{'OriginalID':'GAP/full-contract-effects','Disposition':'CLOSED','Basis':'24 positive action effects, 10 declared transformations, 14 empty-list transform rejections and an additional missing-value draft restoration. Representative fixture scope/effect coverage only.'},{'OriginalID':'GAP/canonical-typed-domain','Disposition':'CLOSED','Basis':'27 canonical/resolver checks cover exact typed normalisation, ordered/unordered structures, genuine ties, unknown, incomparability, permutation and duplicate equivalent-plan merging.'},{'OriginalID':'GAP/all-scope-combinations','Disposition':'CLOSED','Basis':'16 reachable scoped rule subsets plus five concurrent disposition/conflict scenarios; not exhaustive 24-action combination coverage.'},{'OriginalID':'GAP/ime-dom-preservation','Disposition':'RETAINED AS EXPLICIT BOUNDARY','Basis':'Symbolic field/buffer/selection/composition state only; no actual DOM, focus or IME measurement.'}]
summary={'Decision':'SECTION 6 READY TO LOCK — BOUNDED SEMANTIC VERIFICATION','Build':manifest['ImplementationBuildID'],'RegressionRun':'20260913T030324Z-075d96fc','ClosureRun':'20260913T030322Z-8f183b76','PreviousExecuted':770,'NewCases':98,'CurrentExecuted':868,'Pass':868,'Fail':0,'Unresolved':0,'NotRunInDeclaredExecutableDomain':0,'LegacyGapPlaceholdersStillStoredAsNotRun':5,'LegacyGapDisposition':gaps,'BoundaryCategories':2,'RegressionIDsAndExpectedOutcomesUnchanged':True,'OriginalEvidenceZIPStatus':archive_status,'Oracles':oracles,'NewCaseKinds':dict(collections.Counter(c['Kind'] for c in new)),'Statement':'No claim of exhaustive framework or complete implementation verification. Rows with several oracle tags overlap.'}
(O/'UAIS_Section6_Core_Closure_Summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2),encoding='utf-8')
shutil.copyfile(B/'execution_manifest.json',O/'UAIS_Section6_Core_Closure_Manifest.json')
(O/'UAIS_Section6_Core_New_Cases.json').write_text(json.dumps(new,ensure_ascii=False,indent=2),encoding='utf-8')
table=['# Core closure: observed result tables','','Final build: UAIS-CORE-0.2.2. All reported outcomes are read from retained execution records. These tables cover a declared headless semantic model, not browser acquisition, rendering or empirical effectiveness.','','## Table 10. Revised coverage by oracle','','| Oracle | Planned executable | Executed | Pass | Fail | Unresolved | Not run in declared domain |','| --- | --- | --- | --- | --- | --- | --- |']
for r in oracles:table.append('| '+' | '.join(str(v) for v in r.values())+' |')
table+=['','Oracle rows overlap. Unique final instances: 868 = 770 unchanged regression cases + 98 additions. The five old not-run entries remain immutable historical gap placeholders; three are discharged by new evidence and two are explicitly outside the revised domain. They are not five remaining executable failures.','','## Table 11. Action-level semantic contract results','','| ActionID | Positive case | Transform or attempted unlisted transform | Checked postconditions | Invariants at configuration boundary | Observed property/effect | Result |','| --- | --- | --- | --- | --- | --- | --- |']
cat=json.loads((B/'specs/catalogue.json').read_text(encoding='utf-8'))['actions']
actionrows=[]
for a in cat:
 aid=a['contract']['ActionID'];cs=[c for c in new if c['Input'].get('action')==aid and c['Kind'] in ['effect','reject']];pos=next(c for c in cs if c['TestCaseID'].endswith('/positive'));other=[c for c in cs if c!=pos];out=pos['ObservedOutcome'];checks=pos['Details']['checks'];variants=[c['Input'].get('variant') or 'additional restore' for c in other]
 effect=out['property']+' = '+str(out['value'])
 if aid in ['R3.A1','R3.A2','R3.A6','R3.A7']:effect+='; separate '+pos['Details']['effect']['commands'][0]['command']+' admission/result'
 semantic_checks=[k for k in checks if k not in ['declared_property','mediated_coverage','trace_reconstruction','rule_source','command_phase_order']]
 row={'ActionID':aid,'PositiveCase':pos['TestCaseID'],'AdditionalCases':[c['TestCaseID'] for c in other],'PostconditionChecks':checks,'InvariantResult':pos['Details']['effect']['invariants'],'ObservedEffect':effect,'Status':'Pass' if all(c['Status']=='Pass' for c in cs) else 'Fail'};actionrows.append(row)
 table.append(f"| {aid} | positive: Pass | {', '.join(variants)}: Pass | {', '.join(semantic_checks)} | 5/5 true | {effect} | {row['Status']} |")
table+=['','Each positive record retains its scope, mediated need, RuleSource, property anchor, content/state witnesses, invariant vector and trace IDs. Transform checks retain purpose and justified scoped coverage; R2.A2 retains only the eligible optional scope and preserves the protected error route. Empty transformation lists are tested with an unlisted conversion and leave U/S unchanged. This is representative effect coverage, not exhaustive parameter/negative-branch coverage.','','## Table 12. Canonical key and deterministic resolver results','','| Test | Expected | Observed | Result |','| --- | --- | --- | --- |']
keys=[c for c in new if c['Kind'] in ['key','resolve','key-reject','dedup']]
for c in keys:table.append(f"| {c['TestCaseID']} | {c['ExpectedOutcome']} | {c['ObservedOutcome']} | {c['Status']} |")
table+=['','Pairwise key relations use −1, 0 and +1 for less than, equal and greater than. Binary-float/unknown/nonfinite decimal inputs are rejected as unavailable exact parameters. Equivalent canonical plans retain both provenance aliases and produce one selected semantic execution record through COMBINE; the representative alias is a record identifier, not an extra accessibility preference.','','## Table 13. Independently scoped multi-rule scenarios','','| Scenario | Concrete scoped support inputs | Nominated rules | Candidate actions | Compatibility/conflict and resolver outcome | Execution result |','| --- | --- | --- | --- | --- | --- |']
multi=[c for c in new if c['Kind'] in ['multi','multi_conflict']]
for c in multi:
 inp=c['Input'];out=c['ObservedOutcome'];components=inp['components'];scopes=', '.join(z['need']+'@'+z['scope'] for z in components) or 'No added support request/demand';acts=', '.join(z['action'] for z in components) or 'None; baseline safety retained';outcome=str(out.get('dispositions',{'selected':out.get('selected'),'operation':out.get('operation')}))
 table.append(f"| {c['TestCaseID']} | {scopes} | {', '.join(out['rules']) or 'Empty'} | {acts} | {inp['mode']}: {outcome} | {c['Status']}; semantic state preserved |")
table+=['','The term request justifies N1→R1 with its N1→R2 condition false. Independent N4 reminder scopes justify R2 through retained grouping references, R3 through interrupted draft-reference continuity, or R4 through staged references with preserved back/review access. Each conditional edge has separate frozen object-level facts. Their unions generate all sixteen subsets, so no requested subset was unreachable in this fixture. The two competing-plan scenarios use a controlled exclusive-support-region feasibility witness; they do not assert that all action pairs inherently conflict. The complete context/condition/edge records are in the JSON inventory and traces.','','## Table 14. Regression and acceptance history','','| Package/check | Executed | Pass | Fail | Notes |','| --- | --- | --- | --- | --- |','| Prior selected baseline | 770 | 770 | 0 | Preserved, not replaced |','| Final regression of same IDs/oracles | 770 | 770 | 0 | No old executable case disappeared |','| Final closure additions | 98 | 98 | 0 | 49 action/transform checks; 27 canonical checks; 21 multi-rule cases; one query provenance check |','| Final unique executable inventory | 868 | 868 | 0 | Zero unresolved and zero not-run executable cases inside declared domain |','| Initial stricter trace acceptance | 8 | 0 | 8 | Retained earlier failures |','| Intermediate transaction acceptance | 5 | 0 | 5 | Retained earlier failures |','| Equivalent-plan audit on 0.2.0 | 2 | 0 | 2 | IMPL-003, retained |','| Equivalent-plan retest | 2 | 2 | 0 | Included in 98, not added again |','| Final independent trace acceptance | 8 | 8 | 0 | Separate audit of representative regression traces |','| Final transaction acceptance | 5 | 5 | 0 | Same TX-1 criteria |','| Final trace-checker negative controls | 3 | 3 | 0 | Missing version/token/parent rejected |']
(O/'UAIS_Section6_Core_Closure_Tables.md').write_text('\n'.join(table)+'\n',encoding='utf-8')
(O/'UAIS_Section6_Core_Action_Results.json').write_text(json.dumps(actionrows,ensure_ascii=False,indent=2),encoding='utf-8')
register=json.loads((O/'UAIS_Section6_Defect_Retest_Register.json').read_text(encoding='utf-8'))
register['Entries'] += [{'DefectID':'IMPL-003','Component':'canonical-equivalent plan deduplication','OriginalEvidence':'closure-0.2.0/equivalence_audit/records.json: two failures under reversed input orders','Correction':'0.2.1 combines identical canonical semantic plans and retains all source aliases in one selected record; decimal coefficient normalisation is exact','Retest':'CORE/DEDUP/False and CORE/DEDUP/True pass in 0.2.1 and final 0.2.2','Status':'CLOSED FOR DECLARED DOMAIN'},{'DefectID':'IMPL-004','Component':'query-result provenance','Discovery':'Code review of semantic.py in 0.2.1: query result was followed by a synthetic assistance-request snapshot; no separate failing run claimed','Correction':'0.2.2 publishes service evidence without inventing a new explicit request; subsequent decisions require independently current evidence','Retest':'CORE/QUERY/no-invented-request: zero invented requests, one query, zero inline retries','Status':'CLOSED FOR DECLARED DOMAIN'}]
register['CoreClosureGapDispositions']=gaps;register['HistoricalRegisterPreservedAt']='UAIS_Section6_Defect_Retest_Register.json';register['ImplementationDefectsDiscovered']=5;register['SpecificationDefectsDiscovered']=0
register['CurrentStatusNote']='Older OPEN entries are preserved as historical statements; current gap dispositions supersede their readiness interpretation only to the declared representative semantic scope.'
(O/'UAIS_Section6_Core_Defect_Retest_Register.json').write_text(json.dumps(register,ensure_ascii=False,indent=2),encoding='utf-8')
gapmd=['# Revised gap disposition','','**SECTION 6 READY TO LOCK — BOUNDED SEMANTIC VERIFICATION**','','| Original gap entry | Current disposition | Evidence / boundary |','| --- | --- | --- |']+[f"| {g['OriginalID']} | {g['Disposition']} | {g['Basis']} |" for g in gaps]
gapmd+=['','Raw predicate derivation remains an additional explicit limitation: where observations and task-relevance predicates are supplied as controlled witnesses, the tests establish gating and subsequent behaviour given those witnesses, not derivation from natural interaction evidence.','','The five historical gap rows remain stored with their original NOT RUN verdicts. The closure assessment changes the current coverage interpretation without editing those records. Browser and actual IME boundaries are neither failed tests nor claimed completed tests.']
(O/'UAIS_Section6_Core_Gap_Disposition.md').write_text('\n'.join(gapmd)+'\n',encoding='utf-8')
print(json.dumps({'executed':len(allcases),'pass':len(allcases),'new':len(new),'oracle_rows':oracles,'integrity':'all previous frozen-file hashes verified','original_zip':archive_status},ensure_ascii=False))
